name: lumen_flow
description: "Chat With Your AI"
publish_to: "none"
version: 2.0.0+0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3
  intl: any
  flutter_markdown: ^0.7.7+1
  image_picker: ^1.2.0
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_svg: ^2.0.10
  pdf: ^3.11.3
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/prompt/presets-en.json
    - assets/prompt/presets-zh.json
    - assets/prompt/characters/
    - assets/prompt/characters/zh/
    - assets/prompt/characters/en/
    - assets/logo.png
    - assets/platform/
    - pubspec.yaml

