name: lumen_flow
description: "Chat With Your AI"
version: 1.0.5+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_markdown: ^0.7.7+1
  image_picker: ^1.2.0
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/prompt/

